# .eslintrc.yaml
---
  extends: airbnb-base
  env:
    node: true
    mocha: true
    es6: true
  parser: typescript-eslint-parser
  parserOptions:
    sourceType: module
    ecmaFeatures: 
      modules: true
  rules:
    no-undef: 0
    import/prefer-default-export: 0
    quotes: ["error", "double"]
    import/no-unresolved: 0
    semi: ["error", "always"]
    no-restricted-globals: 0
    no-useless-constructor: 0
    no-empty-function: 0
    arrow-parens: 0
    no-unused-vars: 0
    no-underscore-dangle: 0
