# .eslintrc.yaml
---
  extends: airbnb-base
  env:
    node: true
    mocha: true
    es6: true
  parser: typescript-eslint-parser
  parserOptions:
    sourceType: module
    ecmaFeatures: 
      modules: true
  rules:
    no-undef: 0
    import/prefer-default-export: 0
    quotes: ["error", "double"]
    import/no-unresolved: 0
    semi: ["error", "always"]