version: "2"
services:
    atlasp:
        build: .
        restart: always
        container_name: atlasp_server
        image: debian/latest
        environment:
            - NODE_ENV=production
        volumes:
            - .:/var/www:rw
        ports:
            - 3001:3001
        links:
            - mongodb
        depends_on:
            - mongodb
        environment:
            - $CLIENT_ID
            - $CLIENT_SECRET
            - $NODE_ENV
            - $NODE_SECRET
            - $PORT
            - $REDIRECT_URI
            - $REACT_APP_SPREADSHEET
    mongodb:
      restart: always
      container_name: atlasp_database
      image: mongo
      ports:
        - 27017:27017
      volumes:
        - data:/data/db
volumes:
  data:
