version: "2"
services:
    atlasp:
        build: .
        restart: always
        container_name: atlasp_server
        image: debian/latest
        environment:
            - NODE_ENV=production
        volumes:
            - .:/var/www:rw
        ports:
            - 81:81
        links:
            - mongodb
        depends_on:
            - mongodb
    mongodb:
      restart: always
      container_name: atlasp_database
      image: mongo
      ports:
        - 27017:27017
      volumes:
        - data:/data/db
volumes:
  data:
