version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.9.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install --production=false
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn build
  lint:
    docker:
      - image: circleci/node:10.9.0
    steps:
      - checkout
      - run: yarn install --production=false
      - run: yarn lint
  test:
    docker:
      - image: circleci/node:10.9.0
    steps:
      - checkout
      - run: yarn install --production=false
      - run: yarn test
  deploy:
    docker:
      - image: circleci/node:10.9.0
    steps:
      - checkout
      - run:
          name: Add known known hosts
          command: ssh-keyscan $SERVER_URL >> ~/.ssh/known_hosts
      - run: ssh $SERVER 'cd ./atlasP-backend && git pull && yarn && source ~/.bash_profile && (docker kill atlasp_server || true) && (docker rm atlasp_server || true) && docker-compose build && docker-compose up --detach atlasp && docker system prune -f && exit'
workflows:
  version: 2
  build:
    jobs:
      - build
      - lint
      - test
      - deploy:
          requires:
            - build
            - lint
            - test
          filters:
            branches:
              only: master