version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.9.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn build
  lint:
    docker:
      - image: circleci/node:10.9.0
    steps:
      - checkout
      - run: yarn install
      - run: yarn lint
  deploy:
    machine:
      node:
        version: 8.2.0
    steps:
      - checkout
      - run:
          name: Add known known hosts
          command: ssh-keyscan $SERVER_URL >> ~/.ssh/known_hosts
      - run: ssh $SERVER 'cd ./atlasP-backend && git pull && (sudo docker kill $(sudo docker ps -a -q) || true) && (sudo docker rm $(sudo docker ps -a -q) || true) && yarn build && sudo docker-compose build && sudo docker-compose up --detach && exit'
workflows:
  version: 2
  build:
    jobs:
      - build
      - lint
      - deploy:
          requires:
            - build
            - lint
          filters:
            branches:
              only: master