version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.9.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn build
  lint:
    docker:
      - image: circleci/node:10.9.0
    steps:
      - checkout
      - run: yarn install
      - run: yarn lint
  deploy:
    docker:
      - image: circleci/node:10.9.0
    steps:
      - checkout
      - run: ssh $SERVER
      - run: cd ./atlasP-backend
      - run: sudo docker kill $(docker ps -a -q)
      - run: sudo docker-compose build && sudo docker-compose up --detach
      - run: exit
workflows:
  version: 2
  build:
    jobs:
      - build
      - lint
      - deploy:
        requires:
          - build
          - lint